server:
  ssl:
    key-store-type: PKCS12
    key-store: 'classpath:keystore/keystore.p12'
    key-store-password: '123456'
    key-alias: 'cookie-server'

spring:
  resources:
    static-locations:
      - 'file:src/main/resources/static/'
